import { StyleSheet } from 'react-native';
import { borderRadius, borderWidth, colors, shadows, spacing, fontSizes, fontWeights } from '../theme';

/** Shared with projects / app-bottom-sheet / map controls */
export const messagingChrome = {
  unread: colors.error,
  connected: colors.success,
  connecting: colors.warning,
};

export const messagingStyles = StyleSheet.create({
  overlayRoot: {
    ...StyleSheet.absoluteFill,
    zIndex: 2000,
    pointerEvents: 'box-none',
  },
  panelOuter: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 2002,
    borderTopLeftRadius: borderRadius['2xl'],
    borderTopRightRadius: borderRadius['2xl'],
    overflow: 'hidden',
    borderTopWidth: borderWidth.hairline,
    borderTopColor: colors.liquidGlassBorder,
    backgroundColor: colors.background,
    ...shadows.panel,
  },
  resizeHandle: {
    alignItems: 'center',
    paddingTop: spacing.sm,
    paddingBottom: spacing.xs,
    backgroundColor: colors.glassUltra,
  },
  resizeGrab: {
    width: 42,
    height: 4,
    borderRadius: 2,
    backgroundColor: `${colors.white}4D`,
  },
  panelHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    paddingBottom: spacing.sm,
    borderBottomWidth: borderWidth.hairline,
    borderBottomColor: colors.liquidGlassBorderDim,
    backgroundColor: colors.glassUltra,
  },
  panelHeaderTitle: {
    fontSize: 17,
    fontWeight: fontWeights.bold,
    color: colors.white,
    letterSpacing: -0.2,
  },
  iconButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: `${colors.white}1A`,
    borderWidth: borderWidth.hairline,
    borderColor: colors.liquidGlassBorderDim,
    alignItems: 'center',
    justifyContent: 'center',
  },
  panelBody: {
    flex: 1,
    backgroundColor: colors.background,
  },
  wsStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xs,
    borderTopWidth: borderWidth.hairline,
    borderTopColor: colors.liquidGlassBorderDim,
    backgroundColor: colors.surface,
  },
  wsStatusText: {
    color: colors.text.secondary,
    fontSize: fontSizes.xs,
    fontWeight: fontWeights.medium,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.systemGray,
  },
  inboxHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.lg,
    backgroundColor: colors.surface,
  },
  inboxTitle: {
    fontSize: fontSizes.xl,
    fontWeight: fontWeights.bold,
    color: colors.text.primary,
    letterSpacing: -0.3,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: spacing.lg,
    marginVertical: spacing.md,
    paddingHorizontal: spacing.md,
    height: 44,
    borderRadius: borderRadius.md,
    borderWidth: borderWidth.hairline,
    borderColor: colors.border.default,
    backgroundColor: colors.glassUltra,
    gap: spacing.sm,
  },
  searchInput: {
    flex: 1,
    fontSize: fontSizes.lg,
    color: colors.white,
    paddingVertical: 0,
  },
  convItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface,
    minHeight: 44,
    paddingVertical: spacing.md,
    paddingLeft: spacing.lg,
    paddingRight: spacing.sm,
    borderBottomWidth: borderWidth.hairline,
    borderBottomColor: colors.border.default,
    gap: spacing.sm,
  },
  convFavoriteButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: borderRadius.lg,
    backgroundColor: colors.surfaceElevated,
    borderWidth: borderWidth.hairline,
    borderColor: colors.border.default,
    alignItems: 'center',
    justifyContent: 'center',
  },
  convName: {
    color: colors.text.primary,
    fontSize: fontSizes.base,
    fontWeight: fontWeights.medium,
    flex: 1,
    letterSpacing: -0.3,
  },
  convPreview: {
    color: colors.text.secondary,
    fontSize: fontSizes.sm,
    flex: 1,
    lineHeight: 18,
  },
  convTime: {
    color: colors.text.tertiary,
    fontSize: fontSizes.xs,
  },
  unreadBadge: {
    minWidth: 20,
    height: 20,
    borderRadius: borderRadius.full,
    backgroundColor: messagingChrome.unread,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  unreadText: {
    color: colors.white,
    fontSize: fontSizes.xs,
    fontWeight: fontWeights.bold,
  },
  emptyState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.xl,
    gap: spacing.sm,
    backgroundColor: colors.background,
  },
  emptyText: {
    color: colors.text.secondary,
    fontSize: fontSizes.lg,
    textAlign: 'center',
  },
  chatHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    backgroundColor: colors.surface,
    borderBottomWidth: borderWidth.hairline,
    borderBottomColor: colors.border.default,
    gap: spacing.xs,
  },
  messagesList: {
    padding: spacing.lg,
    gap: spacing.sm,
    backgroundColor: colors.background,
  },
  bubbleRowOwn: {
    alignItems: 'flex-end',
  },
  bubbleRowOther: {
    alignItems: 'flex-start',
  },
  senderName: {
    color: colors.text.tertiary,
    fontSize: fontSizes.xs,
    marginBottom: 2,
    marginLeft: 4,
  },
  bubbleOwn: {
    maxWidth: '82%',
    backgroundColor: colors.primary[600],
    borderRadius: borderRadius.lg,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderWidth: borderWidth.hairline,
    borderColor: colors.primary[500],
  },
  bubbleOther: {
    maxWidth: '82%',
    backgroundColor: colors.surfaceElevated,
    borderRadius: borderRadius.lg,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderWidth: borderWidth.hairline,
    borderColor: colors.border.default,
  },
  bubbleText: {
    color: colors.text.primary,
    fontSize: fontSizes.base,
  },
  inputBar: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    padding: spacing.md,
    gap: spacing.sm,
    borderTopWidth: borderWidth.hairline,
    borderTopColor: colors.border.default,
    backgroundColor: colors.surface,
  },
  textInput: {
    flex: 1,
    maxHeight: 100,
    minHeight: 44,
    borderRadius: borderRadius.md,
    borderWidth: borderWidth.hairline,
    borderColor: colors.border.default,
    backgroundColor: colors.glassUltra,
    color: colors.white,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    fontSize: fontSizes.lg,
  },
  sendBtn: {
    width: 44,
    height: 44,
    borderRadius: borderRadius.lg,
    backgroundColor: colors.primary[500],
    borderWidth: borderWidth.hairline,
    borderColor: colors.primary[500],
    alignItems: 'center',
    justifyContent: 'center',
    ...shadows.glowBlue,
  },
  contactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface,
    minHeight: 44,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    borderBottomWidth: borderWidth.hairline,
    borderBottomColor: colors.border.default,
    gap: spacing.sm,
  },
  linkText: {
    color: colors.primary[500],
    fontSize: fontSizes.base,
    fontWeight: fontWeights.semibold,
  },
  inboxFilterRow: {
    paddingTop: spacing.lg,
    paddingBottom: spacing.md,
    paddingHorizontal: spacing.lg,
    backgroundColor: colors.surface,
    borderBottomWidth: borderWidth.hairline,
    borderBottomColor: colors.border.default,
  },
  inboxFilterStrip: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: spacing.sm,
    width: '100%',
  },
  filterChip: {
    flex: 1,
    minWidth: 0,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.xs,
    borderRadius: borderRadius.md,
    borderWidth: borderWidth.hairline,
    borderColor: colors.border.default,
    backgroundColor: colors.glassUltra,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterChipActive: {
    backgroundColor: `${colors.primary[500]}33`,
    borderColor: colors.primary[500],
  },
  filterChipText: {
    color: colors.text.secondary,
    fontSize: fontSizes.xs,
    fontWeight: fontWeights.semibold,
    textAlign: 'center',
  },
  filterChipTextActive: {
    color: colors.primary[500],
  },
  reactionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
    marginTop: 4,
  },
  reactionChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: borderRadius.md,
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    borderWidth: borderWidth.hairline,
    borderColor: colors.border.default,
  },
  reactionChipActive: {
    backgroundColor: `${colors.primary[500]}40`,
    borderColor: colors.primary[500],
  },
  reactionPicker: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
    padding: spacing.sm,
    marginBottom: spacing.xs,
    borderRadius: borderRadius.md,
    backgroundColor: colors.surfaceElevated,
    borderWidth: borderWidth.hairline,
    borderColor: colors.border.default,
  },
  reactionEmojiBtn: {
    padding: 4,
    minWidth: 32,
    alignItems: 'center',
  },
  chatImage: {
    width: 200,
    height: 200,
    borderRadius: borderRadius.md,
    backgroundColor: colors.surfaceElevated,
  },
  attachMenu: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderTopWidth: borderWidth.hairline,
    borderTopColor: colors.border.default,
    backgroundColor: colors.surface,
  },
  attachMenuBtn: {
    alignItems: 'center',
    gap: 4,
    padding: spacing.sm,
    minWidth: 72,
  },
  attachMenuLabel: {
    color: colors.text.secondary,
    fontSize: fontSizes.xs,
    fontWeight: fontWeights.medium,
  },
  groupActionBar: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    paddingBottom: spacing.md,
    gap: spacing.sm,
    borderTopWidth: borderWidth.hairline,
    borderTopColor: colors.border.default,
    backgroundColor: colors.surface,
  },
  groupDeleteBtn: {
    minHeight: 44,
    borderRadius: borderRadius.lg,
    backgroundColor: `${colors.error}26`,
    borderWidth: borderWidth.hairline,
    borderColor: colors.error,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
  },
  groupPrimaryBtn: {
    minHeight: 44,
    borderRadius: borderRadius.lg,
    backgroundColor: colors.primary[500],
    borderWidth: borderWidth.hairline,
    borderColor: colors.primary[500],
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
    ...shadows.glowBlue,
  },
  groupPrimaryBtnText: {
    color: colors.white,
    fontSize: fontSizes.base,
    fontWeight: fontWeights.semibold,
  },
  groupDeleteBtnText: {
    color: colors.error,
    fontSize: fontSizes.base,
    fontWeight: fontWeights.semibold,
  },
  groupSearchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    minHeight: 44,
    borderRadius: borderRadius.md,
    borderWidth: borderWidth.hairline,
    borderColor: colors.border.default,
    backgroundColor: colors.glassUltra,
    gap: spacing.sm,
  },
  memberTagsSection: {
    minHeight: 36,
    paddingVertical: spacing.xs,
  },
  memberTagsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  memberTagsHint: {
    color: colors.text.tertiary,
    fontSize: fontSizes.sm,
    fontStyle: 'italic',
  },
  memberTagChip: {
    flexDirection: 'row',
    alignItems: 'center',
    maxWidth: '100%',
    paddingLeft: spacing.md,
    paddingRight: spacing.xs,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.full,
    backgroundColor: `${colors.primary[500]}33`,
    borderWidth: borderWidth.hairline,
    borderColor: colors.primary[500],
    gap: spacing.xs,
  },
  memberTagText: {
    color: colors.text.primary,
    fontSize: fontSizes.sm,
    fontWeight: fontWeights.medium,
    flexShrink: 1,
  },
  memberTagRemove: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
  },
  contactRowSelected: {
    backgroundColor: `${colors.primary[500]}22`,
  },
  dateSeparator: {
    alignSelf: 'center',
    marginVertical: spacing.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.full,
    backgroundColor: colors.glassUltra,
  },
  dateSeparatorText: {
    color: colors.text.tertiary,
    fontSize: fontSizes.xs,
    fontWeight: fontWeights.semibold,
  },
  bubbleMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 2,
    alignSelf: 'flex-end',
  },
  bubbleTime: {
    color: colors.text.tertiary,
    fontSize: 10,
  },
  bubbleTimeOwn: {
    color: 'rgba(255,255,255,0.65)',
    fontSize: 10,
  },
  editedLabel: {
    color: colors.text.tertiary,
    fontSize: 10,
    fontStyle: 'italic',
  },
  fileAttachment: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    padding: spacing.md,
  },
  lightboxBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.92)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  lightboxClose: {
    position: 'absolute',
    top: 48,
    right: 20,
    zIndex: 2,
    padding: spacing.sm,
  },
  lightboxImage: {
    width: '100%',
    height: '80%',
  },
  pendingAttachRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    backgroundColor: colors.surface,
  },
  pendingAttachChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingLeft: spacing.sm,
    paddingRight: spacing.xs,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.md,
    backgroundColor: colors.glassUltra,
    borderWidth: borderWidth.hairline,
    borderColor: colors.border.default,
  },
  tabUnreadBadge: {
    position: 'absolute',
    top: -4,
    right: -10,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: colors.error,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 3,
  },
  tabUnreadText: {
    color: colors.white,
    fontSize: 9,
    fontWeight: fontWeights.bold,
  },
});
