"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.fontWeights = exports.fontSizes = exports.shadows = exports.borderWidth = exports.borderRadius = exports.spacing = exports.colors = void 0;
var defaultTheme_1 = require("./defaultTheme");
Object.defineProperty(exports, "colors", { enumerable: true, get: function () { return defaultTheme_1.colors; } });
Object.defineProperty(exports, "spacing", { enumerable: true, get: function () { return defaultTheme_1.spacing; } });
Object.defineProperty(exports, "borderRadius", { enumerable: true, get: function () { return defaultTheme_1.borderRadius; } });
Object.defineProperty(exports, "borderWidth", { enumerable: true, get: function () { return defaultTheme_1.borderWidth; } });
Object.defineProperty(exports, "shadows", { enumerable: true, get: function () { return defaultTheme_1.shadows; } });
var typography_1 = require("./typography");
Object.defineProperty(exports, "fontSizes", { enumerable: true, get: function () { return typography_1.fontSizes; } });
Object.defineProperty(exports, "fontWeights", { enumerable: true, get: function () { return typography_1.fontWeights; } });
