"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.messagingStyles = exports.messagingChrome = void 0;
const react_native_1 = require("react-native");
const theme_1 = require("../theme");
/** Shared with projects / app-bottom-sheet / map controls */
exports.messagingChrome = {
    unread: theme_1.colors.error,
    connected: theme_1.colors.success,
    connecting: theme_1.colors.warning,
};
exports.messagingStyles = react_native_1.StyleSheet.create({
    overlayRoot: {
        ...react_native_1.StyleSheet.absoluteFill,
        zIndex: 2000,
        pointerEvents: 'box-none',
    },
    panelOuter: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: 2002,
        borderTopLeftRadius: theme_1.borderRadius['2xl'],
        borderTopRightRadius: theme_1.borderRadius['2xl'],
        overflow: 'hidden',
        borderTopWidth: theme_1.borderWidth.hairline,
        borderTopColor: theme_1.colors.liquidGlassBorder,
        backgroundColor: theme_1.colors.background,
        ...theme_1.shadows.panel,
    },
    resizeHandle: {
        alignItems: 'center',
        paddingTop: theme_1.spacing.sm,
        paddingBottom: theme_1.spacing.xs,
        backgroundColor: theme_1.colors.glassUltra,
    },
    resizeGrab: {
        width: 42,
        height: 4,
        borderRadius: 2,
        backgroundColor: `${theme_1.colors.white}4D`,
    },
    panelHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: theme_1.spacing.lg,
        paddingTop: theme_1.spacing.sm,
        paddingBottom: theme_1.spacing.sm,
        borderBottomWidth: theme_1.borderWidth.hairline,
        borderBottomColor: theme_1.colors.liquidGlassBorderDim,
        backgroundColor: theme_1.colors.glassUltra,
    },
    panelHeaderTitle: {
        fontSize: 17,
        fontWeight: theme_1.fontWeights.bold,
        color: theme_1.colors.white,
        letterSpacing: -0.2,
    },
    iconButton: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: `${theme_1.colors.white}1A`,
        borderWidth: theme_1.borderWidth.hairline,
        borderColor: theme_1.colors.liquidGlassBorderDim,
        alignItems: 'center',
        justifyContent: 'center',
    },
    panelBody: {
        flex: 1,
        backgroundColor: theme_1.colors.background,
    },
    wsStatus: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        paddingHorizontal: theme_1.spacing.lg,
        paddingVertical: theme_1.spacing.xs,
        borderTopWidth: theme_1.borderWidth.hairline,
        borderTopColor: theme_1.colors.liquidGlassBorderDim,
        backgroundColor: theme_1.colors.surface,
    },
    wsStatusText: {
        color: theme_1.colors.text.secondary,
        fontSize: theme_1.fontSizes.xs,
        fontWeight: theme_1.fontWeights.medium,
    },
    statusDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: theme_1.colors.systemGray,
    },
    inboxHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: theme_1.spacing.lg,
        paddingTop: theme_1.spacing.md,
        paddingBottom: theme_1.spacing.lg,
        backgroundColor: theme_1.colors.surface,
    },
    inboxTitle: {
        fontSize: theme_1.fontSizes.xl,
        fontWeight: theme_1.fontWeights.bold,
        color: theme_1.colors.text.primary,
        letterSpacing: -0.3,
    },
    searchBar: {
        flexDirection: 'row',
        alignItems: 'center',
        marginHorizontal: theme_1.spacing.lg,
        marginVertical: theme_1.spacing.md,
        paddingHorizontal: theme_1.spacing.md,
        height: 44,
        borderRadius: theme_1.borderRadius.md,
        borderWidth: theme_1.borderWidth.hairline,
        borderColor: theme_1.colors.border.default,
        backgroundColor: theme_1.colors.glassUltra,
        gap: theme_1.spacing.sm,
    },
    searchInput: {
        flex: 1,
        fontSize: theme_1.fontSizes.lg,
        color: theme_1.colors.white,
        paddingVertical: 0,
    },
    convItem: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: theme_1.colors.surface,
        minHeight: 44,
        paddingVertical: theme_1.spacing.md,
        paddingLeft: theme_1.spacing.lg,
        paddingRight: theme_1.spacing.sm,
        borderBottomWidth: theme_1.borderWidth.hairline,
        borderBottomColor: theme_1.colors.border.default,
        gap: theme_1.spacing.sm,
    },
    convFavoriteButton: {
        width: 40,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
    },
    avatar: {
        width: 44,
        height: 44,
        borderRadius: theme_1.borderRadius.lg,
        backgroundColor: theme_1.colors.surfaceElevated,
        borderWidth: theme_1.borderWidth.hairline,
        borderColor: theme_1.colors.border.default,
        alignItems: 'center',
        justifyContent: 'center',
    },
    convName: {
        color: theme_1.colors.text.primary,
        fontSize: theme_1.fontSizes.base,
        fontWeight: theme_1.fontWeights.medium,
        flex: 1,
        letterSpacing: -0.3,
    },
    convPreview: {
        color: theme_1.colors.text.secondary,
        fontSize: theme_1.fontSizes.sm,
        flex: 1,
        lineHeight: 18,
    },
    convTime: {
        color: theme_1.colors.text.tertiary,
        fontSize: theme_1.fontSizes.xs,
    },
    unreadBadge: {
        minWidth: 20,
        height: 20,
        borderRadius: theme_1.borderRadius.full,
        backgroundColor: exports.messagingChrome.unread,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 6,
    },
    unreadText: {
        color: theme_1.colors.white,
        fontSize: theme_1.fontSizes.xs,
        fontWeight: theme_1.fontWeights.bold,
    },
    emptyState: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        padding: theme_1.spacing.xl,
        gap: theme_1.spacing.sm,
        backgroundColor: theme_1.colors.background,
    },
    emptyText: {
        color: theme_1.colors.text.secondary,
        fontSize: theme_1.fontSizes.lg,
        textAlign: 'center',
    },
    chatHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: theme_1.spacing.md,
        paddingVertical: theme_1.spacing.md,
        backgroundColor: theme_1.colors.surface,
        borderBottomWidth: theme_1.borderWidth.hairline,
        borderBottomColor: theme_1.colors.border.default,
        gap: theme_1.spacing.xs,
    },
    messagesList: {
        padding: theme_1.spacing.lg,
        gap: theme_1.spacing.sm,
        backgroundColor: theme_1.colors.background,
    },
    bubbleRowOwn: {
        alignItems: 'flex-end',
    },
    bubbleRowOther: {
        alignItems: 'flex-start',
    },
    senderName: {
        color: theme_1.colors.text.tertiary,
        fontSize: theme_1.fontSizes.xs,
        marginBottom: 2,
        marginLeft: 4,
    },
    bubbleOwn: {
        maxWidth: '82%',
        backgroundColor: theme_1.colors.primary[600],
        borderRadius: theme_1.borderRadius.lg,
        paddingHorizontal: theme_1.spacing.md,
        paddingVertical: theme_1.spacing.sm,
        borderWidth: theme_1.borderWidth.hairline,
        borderColor: theme_1.colors.primary[500],
    },
    bubbleOther: {
        maxWidth: '82%',
        backgroundColor: theme_1.colors.surfaceElevated,
        borderRadius: theme_1.borderRadius.lg,
        paddingHorizontal: theme_1.spacing.md,
        paddingVertical: theme_1.spacing.sm,
        borderWidth: theme_1.borderWidth.hairline,
        borderColor: theme_1.colors.border.default,
    },
    bubbleText: {
        color: theme_1.colors.text.primary,
        fontSize: theme_1.fontSizes.base,
    },
    inputBar: {
        flexDirection: 'row',
        alignItems: 'flex-end',
        padding: theme_1.spacing.md,
        gap: theme_1.spacing.sm,
        borderTopWidth: theme_1.borderWidth.hairline,
        borderTopColor: theme_1.colors.border.default,
        backgroundColor: theme_1.colors.surface,
    },
    textInput: {
        flex: 1,
        maxHeight: 100,
        minHeight: 44,
        borderRadius: theme_1.borderRadius.md,
        borderWidth: theme_1.borderWidth.hairline,
        borderColor: theme_1.colors.border.default,
        backgroundColor: theme_1.colors.glassUltra,
        color: theme_1.colors.white,
        paddingHorizontal: theme_1.spacing.md,
        paddingVertical: theme_1.spacing.sm,
        fontSize: theme_1.fontSizes.lg,
    },
    sendBtn: {
        width: 44,
        height: 44,
        borderRadius: theme_1.borderRadius.lg,
        backgroundColor: theme_1.colors.primary[500],
        borderWidth: theme_1.borderWidth.hairline,
        borderColor: theme_1.colors.primary[500],
        alignItems: 'center',
        justifyContent: 'center',
        ...theme_1.shadows.glowBlue,
    },
    contactRow: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: theme_1.colors.surface,
        minHeight: 44,
        paddingVertical: theme_1.spacing.md,
        paddingHorizontal: theme_1.spacing.lg,
        borderBottomWidth: theme_1.borderWidth.hairline,
        borderBottomColor: theme_1.colors.border.default,
        gap: theme_1.spacing.sm,
    },
    linkText: {
        color: theme_1.colors.primary[500],
        fontSize: theme_1.fontSizes.base,
        fontWeight: theme_1.fontWeights.semibold,
    },
    inboxFilterRow: {
        paddingTop: theme_1.spacing.lg,
        paddingBottom: theme_1.spacing.md,
        paddingHorizontal: theme_1.spacing.lg,
        backgroundColor: theme_1.colors.surface,
        borderBottomWidth: theme_1.borderWidth.hairline,
        borderBottomColor: theme_1.colors.border.default,
    },
    inboxFilterStrip: {
        flexDirection: 'row',
        alignItems: 'stretch',
        gap: theme_1.spacing.sm,
        width: '100%',
    },
    filterChip: {
        flex: 1,
        minWidth: 0,
        paddingVertical: theme_1.spacing.sm,
        paddingHorizontal: theme_1.spacing.xs,
        borderRadius: theme_1.borderRadius.md,
        borderWidth: theme_1.borderWidth.hairline,
        borderColor: theme_1.colors.border.default,
        backgroundColor: theme_1.colors.glassUltra,
        alignItems: 'center',
        justifyContent: 'center',
    },
    filterChipActive: {
        backgroundColor: `${theme_1.colors.primary[500]}33`,
        borderColor: theme_1.colors.primary[500],
    },
    filterChipText: {
        color: theme_1.colors.text.secondary,
        fontSize: theme_1.fontSizes.xs,
        fontWeight: theme_1.fontWeights.semibold,
        textAlign: 'center',
    },
    filterChipTextActive: {
        color: theme_1.colors.primary[500],
    },
    reactionRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 4,
        marginTop: 4,
    },
    reactionChip: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: theme_1.borderRadius.md,
        backgroundColor: 'rgba(255, 255, 255, 0.12)',
        borderWidth: theme_1.borderWidth.hairline,
        borderColor: theme_1.colors.border.default,
    },
    reactionChipActive: {
        backgroundColor: `${theme_1.colors.primary[500]}40`,
        borderColor: theme_1.colors.primary[500],
    },
    reactionPicker: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 4,
        padding: theme_1.spacing.sm,
        marginBottom: theme_1.spacing.xs,
        borderRadius: theme_1.borderRadius.md,
        backgroundColor: theme_1.colors.surfaceElevated,
        borderWidth: theme_1.borderWidth.hairline,
        borderColor: theme_1.colors.border.default,
    },
    reactionEmojiBtn: {
        padding: 4,
        minWidth: 32,
        alignItems: 'center',
    },
    chatImage: {
        width: 200,
        height: 200,
        borderRadius: theme_1.borderRadius.md,
        backgroundColor: theme_1.colors.surfaceElevated,
    },
    attachMenu: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-around',
        paddingVertical: theme_1.spacing.sm,
        paddingHorizontal: theme_1.spacing.md,
        borderTopWidth: theme_1.borderWidth.hairline,
        borderTopColor: theme_1.colors.border.default,
        backgroundColor: theme_1.colors.surface,
    },
    attachMenuBtn: {
        alignItems: 'center',
        gap: 4,
        padding: theme_1.spacing.sm,
        minWidth: 72,
    },
    attachMenuLabel: {
        color: theme_1.colors.text.secondary,
        fontSize: theme_1.fontSizes.xs,
        fontWeight: theme_1.fontWeights.medium,
    },
    groupActionBar: {
        paddingHorizontal: theme_1.spacing.lg,
        paddingTop: theme_1.spacing.sm,
        paddingBottom: theme_1.spacing.md,
        gap: theme_1.spacing.sm,
        borderTopWidth: theme_1.borderWidth.hairline,
        borderTopColor: theme_1.colors.border.default,
        backgroundColor: theme_1.colors.surface,
    },
    groupDeleteBtn: {
        minHeight: 44,
        borderRadius: theme_1.borderRadius.lg,
        backgroundColor: `${theme_1.colors.error}26`,
        borderWidth: theme_1.borderWidth.hairline,
        borderColor: theme_1.colors.error,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: theme_1.spacing.lg,
    },
    groupPrimaryBtn: {
        minHeight: 44,
        borderRadius: theme_1.borderRadius.lg,
        backgroundColor: theme_1.colors.primary[500],
        borderWidth: theme_1.borderWidth.hairline,
        borderColor: theme_1.colors.primary[500],
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: theme_1.spacing.lg,
        ...theme_1.shadows.glowBlue,
    },
    groupPrimaryBtnText: {
        color: theme_1.colors.white,
        fontSize: theme_1.fontSizes.base,
        fontWeight: theme_1.fontWeights.semibold,
    },
    groupDeleteBtnText: {
        color: theme_1.colors.error,
        fontSize: theme_1.fontSizes.base,
        fontWeight: theme_1.fontWeights.semibold,
    },
    groupSearchBar: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: theme_1.spacing.md,
        minHeight: 44,
        borderRadius: theme_1.borderRadius.md,
        borderWidth: theme_1.borderWidth.hairline,
        borderColor: theme_1.colors.border.default,
        backgroundColor: theme_1.colors.glassUltra,
        gap: theme_1.spacing.sm,
    },
    memberTagsSection: {
        minHeight: 36,
        paddingVertical: theme_1.spacing.xs,
    },
    memberTagsWrap: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: theme_1.spacing.xs,
    },
    memberTagsHint: {
        color: theme_1.colors.text.tertiary,
        fontSize: theme_1.fontSizes.sm,
        fontStyle: 'italic',
    },
    memberTagChip: {
        flexDirection: 'row',
        alignItems: 'center',
        maxWidth: '100%',
        paddingLeft: theme_1.spacing.md,
        paddingRight: theme_1.spacing.xs,
        paddingVertical: theme_1.spacing.xs,
        borderRadius: theme_1.borderRadius.full,
        backgroundColor: `${theme_1.colors.primary[500]}33`,
        borderWidth: theme_1.borderWidth.hairline,
        borderColor: theme_1.colors.primary[500],
        gap: theme_1.spacing.xs,
    },
    memberTagText: {
        color: theme_1.colors.text.primary,
        fontSize: theme_1.fontSizes.sm,
        fontWeight: theme_1.fontWeights.medium,
        flexShrink: 1,
    },
    memberTagRemove: {
        width: 22,
        height: 22,
        borderRadius: 11,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.12)',
    },
    contactRowSelected: {
        backgroundColor: `${theme_1.colors.primary[500]}22`,
    },
    dateSeparator: {
        alignSelf: 'center',
        marginVertical: theme_1.spacing.md,
        paddingHorizontal: theme_1.spacing.md,
        paddingVertical: theme_1.spacing.xs,
        borderRadius: theme_1.borderRadius.full,
        backgroundColor: theme_1.colors.glassUltra,
    },
    dateSeparatorText: {
        color: theme_1.colors.text.tertiary,
        fontSize: theme_1.fontSizes.xs,
        fontWeight: theme_1.fontWeights.semibold,
    },
    bubbleMetaRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        marginTop: 2,
        alignSelf: 'flex-end',
    },
    bubbleTime: {
        color: theme_1.colors.text.tertiary,
        fontSize: 10,
    },
    bubbleTimeOwn: {
        color: 'rgba(255,255,255,0.65)',
        fontSize: 10,
    },
    editedLabel: {
        color: theme_1.colors.text.tertiary,
        fontSize: 10,
        fontStyle: 'italic',
    },
    fileAttachment: {
        alignItems: 'center',
        justifyContent: 'center',
        gap: theme_1.spacing.xs,
        padding: theme_1.spacing.md,
    },
    lightboxBackdrop: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.92)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    lightboxClose: {
        position: 'absolute',
        top: 48,
        right: 20,
        zIndex: 2,
        padding: theme_1.spacing.sm,
    },
    lightboxImage: {
        width: '100%',
        height: '80%',
    },
    pendingAttachRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: theme_1.spacing.xs,
        paddingHorizontal: theme_1.spacing.md,
        paddingTop: theme_1.spacing.sm,
        backgroundColor: theme_1.colors.surface,
    },
    pendingAttachChip: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        paddingLeft: theme_1.spacing.sm,
        paddingRight: theme_1.spacing.xs,
        paddingVertical: theme_1.spacing.xs,
        borderRadius: theme_1.borderRadius.md,
        backgroundColor: theme_1.colors.glassUltra,
        borderWidth: theme_1.borderWidth.hairline,
        borderColor: theme_1.colors.border.default,
    },
    tabUnreadBadge: {
        position: 'absolute',
        top: -4,
        right: -10,
        minWidth: 16,
        height: 16,
        borderRadius: 8,
        backgroundColor: theme_1.colors.error,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 3,
    },
    tabUnreadText: {
        color: theme_1.colors.white,
        fontSize: 9,
        fontWeight: theme_1.fontWeights.bold,
    },
});
